blueberry:
  optimizeActuatorUrl: http://localhost:9603
  operateActuatorUrl: http://localhost:9601
  tasklistActuatorUrl: http://localhost:9602
  zeebeActuatorUrl: http://localhost:9600
  kubeConfigWindows: \\wsl$\Ubuntu\home\pym\config
  kubeConfig: \\wsl.localhost\Ubuntu\home\pym\.kube\config

  # THis information are temporary. They must come from the pod itself
  operateRepository: operaterepository
  tasklistRepository: tasklistrepository
  optimizeRepository : optimizerepository

  elasticsearch:
    containerType: azure
    containerName: elasticsearchcontainer
    operateContainerBasePath: /operate
    tasklistContainerBasePath: /tasklist
    optimizeContainerBasePath: /optimize
    zeebeRecordContainerBasePath: /zeeberecord

  zeebe:
    containerType: AZURE
    containerName: zeebcontainer
    zeebeRecordRepository: camunda_zeebe_records_backup



server:
  port: 9082

# List of port to access
# kubectl port-forward svc/camunda-zeebe-gateway 26500:26500 -n camunda
# kubectl port-forward svc/camunda-zeebe-gateway 9600:9600 -n camunda
# kubectl port-forward svc/camunda-operate 8081:80 -n camunda
# kubectl port-forward svc/camunda-tasklist 8082:80 -n camunda
# kubectl port-forward svc/camunda-elasticsearch 9200:9200 -n camunda
# port forward component acuator
# kubectl port-forward svc/camunda-operate 9601:9600 -n camunda
# kubectl port-forward svc/camunda-tasklist 9602:9600 -n camunda
# kubectl port-forward svc/camunda-optimize 9603:8092 -n camunda
# -------------------- Self Manage
camunda:
  client:
    mode: selfmanaged
    zeebe:
      enabled: true
      gatewayUrl: http://localhost:26500
      preferRestOverGrpc: false
      executionThreads: 200
      defaults:
        maxJobsActive: 58

  tasklist:
    enabled: false
operate:
  client:
    profile: simple
    enabled: true
    base-url: http://localhost:8081
    session-timeout: PT10M
    username: demo
    password: demo



logging.level.root: INFO


# return message with BAD_REQUEST to the client
server.error.include-message: always

# Spring Boot Configuration
spring.application.name: Blueberry

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
